spring:
  datasource:
    url: jdbc:mysql://localhost:3306/morty?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.morty: trace
mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml